# Generated by Django 5.0.7 on 2025-09-21 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('servings', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(default='g', max_length=10)),
                ('kcal_per100g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('carbs_per100g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('protein_per100g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fat_per100g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sugar_per100g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sodium_per100g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            options={
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_g', models.DecimalField(decimal_places=2, max_digits=9)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nutrition.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.recipe')),
            ],
        ),
    ]
