# Generated by Django 5.0.7 on 2025-09-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_recipe_piece_weight_g'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='density_g_per_ml',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='amount_ml',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
