# Generated by Django 5.0.7 on 2025-09-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_ingredient_density_g_per_ml_recipeitem_amount_ml'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='yield_rate',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
    ]
