# Generated by Django 5.0.7 on 2025-09-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_recipe_yield_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, choices=[('SPONGE', '스폰지/제누와즈'), ('CHIFFON', '시폰케이크'), ('POUND', '버터/파운드'), ('BROWNIE', '브라우니'), ('MUFFIN', '머핀'), ('BAKED_CHEESE', '치즈케이크(구움)'), ('NOBAKE_CHEESE', '치즈케이크(냉장)'), ('TART', '타르트/파이'), ('TART_SHELL', '타르트쉘'), ('COOKIE', '쿠키'), ('MACARON', '마카롱'), ('CHOUX', '슈'), ('CROISSANT', '크루아상/데니시'), ('BRIOCHE', '브리오슈'), ('SHOKUPAN', '식빵'), ('BAGUETTE', '바게트/하드빵'), ('CREAM', '생크림/크림'), ('CUSTARD', '커스터드'), ('GANACHE', '가나슈/글레이즈')], max_length=32),
        ),
        migrations.AddField(
            model_name='recipe',
            name='post_bake_weight_g',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='pre_bake_weight_g',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='yield_rate',
            field=models.DecimalField(decimal_places=2, default=100, help_text='굽고 식힌 뒤 남는 비율(%) — 예: 92', max_digits=5),
        ),
    ]
