# Generated by Django 5.0.7 on 2025-09-22 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0007_update_verbose_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': '재료', 'verbose_name_plural': '재료 목록'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': '레시피', 'verbose_name_plural': '레시피 목록'},
        ),
        migrations.AlterModelOptions(
            name='recipeitem',
            options={'verbose_name': '레시피 재료', 'verbose_name_plural': '레시피 재료 목록'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='브랜드'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbs_per100g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='탄수화물(100g당)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='contains_egg',
            field=models.BooleanField(default=False, verbose_name='계란 포함'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='contains_gluten',
            field=models.BooleanField(default=False, verbose_name='글루텐 포함'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='contains_milk',
            field=models.BooleanField(default=False, verbose_name='유제품 포함'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='contains_nuts',
            field=models.BooleanField(default=False, verbose_name='견과류 포함'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='contains_shellfish',
            field=models.BooleanField(default=False, verbose_name='갑각류 포함'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='contains_soy',
            field=models.BooleanField(default=False, verbose_name='대두 포함'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='density_g_per_ml',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='액체 재료의 밀도 (선택사항)', max_digits=6, null=True, verbose_name='밀도(g/mL)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat_per100g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='지방(100g당)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='kcal_per100g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='칼로리(100g당)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=200, verbose_name='제품명'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein_per100g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='단백질(100g당)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sodium_per100g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='나트륨(100g당)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sugar_per100g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='당류(100g당)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(default='g', max_length=10, verbose_name='단위'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, choices=[('SPONGE', '스폰지/제누와즈'), ('CHIFFON', '시폰케이크'), ('POUND', '버터/파운드'), ('BROWNIE', '브라우니'), ('MUFFIN', '머핀'), ('BAKED_CHEESE', '치즈케이크(구움)'), ('NOBAKE_CHEESE', '치즈케이크(냉장)'), ('TART', '타르트/파이'), ('TART_SHELL', '타르트쉘'), ('COOKIE', '쿠키'), ('MACARON', '마카롱'), ('CHOUX', '슈'), ('CROISSANT', '크루아상/데니시'), ('BRIOCHE', '브리오슈'), ('SHOKUPAN', '식빵'), ('BAGUETTE', '바게트/하드빵'), ('CREAM', '생크림/크림'), ('CUSTARD', '커스터드'), ('GANACHE', '가나슈/글레이즈')], max_length=32, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.TextField(blank=True, verbose_name='메모'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='piece_weight_g',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='1조각(1회 제공분)의 목표 중량을 입력하면 제공횟수가 자동 계산됩니다', max_digits=8, null=True, verbose_name='1조각 중량(g)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='post_bake_weight_g',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='굽기 후 중량(g)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pre_bake_weight_g',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='굽기 전 중량(g)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.PositiveIntegerField(default=1, help_text='총 몇 조각으로 나눌지 입력', verbose_name='제공 횟수'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=200, verbose_name='레시피명'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='yield_rate',
            field=models.DecimalField(decimal_places=2, default=100, help_text='굽고 식힌 뒤 남는 비율 (예: 92)', max_digits=5, verbose_name='수율(%)'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='amount_g',
            field=models.DecimalField(decimal_places=2, help_text='그램 단위로 입력', max_digits=9, verbose_name='사용량(g)'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='amount_ml',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='액체 재료의 경우 mL로 입력 (밀도가 입력된 재료만)', max_digits=9, null=True, verbose_name='사용량(mL)'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nutrition.ingredient', verbose_name='재료'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.recipe', verbose_name='레시피'),
        ),
    ]
